apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # echo -n "rootpassword" | base64
  mysql-root-password: cm9vdHBhc3N3b3Jk
  # echo -n "apppassword" | base64
  mysql-app-password: YXBwcGFzc3dvcmQ=
  # base64 encoded connection string
  # Server=mysql-0.mysql;Database=appdb;User=appuser;Password=apppassword;
  connection-string: U2VydmVyPW15c3FsLTAubXlzcWw7RGF0YWJhc2U9YXBwZGI7VXNlcj1hcHB1c2VyO1Bhc3N3b3JkPWFwcHBhc3N3b3Jk
