apiVersion: v1
kind: Namespace
metadata:
  name: k8sexplorer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graceful-workload
  namespace: k8sexplorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graceful-workload
  template:
    metadata:
      labels:
        app: graceful-workload
    spec:
      terminationGracePeriodSeconds: 45
      containers:
        - name: workload
          image: localhost/k8s-test-workload:local
          imagePullPolicy: Never
          env:
            - name: PATCH_AT
              value: ""
            - name: PATCH_TIME_ZONE
              value: ""
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
