apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    type: local
    storage-tier: fast
spec:
  storageClassName: manual-local
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce       # Only 1 node can mount R/W at a time
  persistentVolumeReclaimPolicy: Retain  # Keep data when PVC deleted
  local:
    path: /mnt/data/local-pv             # Must exist on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube                # Pin to this specific node
